# -*- coding: utf-8 -*-
"""Superstore_sales_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aBCRhXIGX-5YFeXi74uSX4eqKow6W3jQ
"""

#superstore dataset

import kagglehub

#download latest version
path = kagglehub.dataset_download("himanshuuike/superstore-sales-dataset")

print("path the dataset files:",path)

import os

print(os.listdir(path))

import pandas as pd

df = pd.read_csv(os.path.join(path,"samplesuperstore.csv"))

print("dataset loaded successfully")

""" Task 1 - Inspect the Superstore Dataset

Display:

1. First 10 rows
2. Last 10 rows
3. Number of rows and columns
4. Column names

"""

display(df.head(10))
display(df.tail(10))
print("shape:", df.shape)


print("columns:")
print(df.columns.tolist())

"""## Task 2 - Select Important Columns

Display only:

- Customer Name
- Category
- Sales
- Profit

Show the first 10 records."""

df[
    ["Customer Name","Category","Sales","Profit"]
].head(10)

""" Task 3 - High Sales Record

Find all record where sales is greater than 500.

Display the first 10 results."""

high_sales = df[df["Sales"] > 500]

print("Number:", len(high_sales))

display(high_sales.head(10))

""" ## Task 4 - Filter by Category

Display records belonging to the Technology category.

show:

- Customer name
- Product name
- Sales
- Profit

Display the first 10 records. """

df[df["Category"] == "Technology"][["Customer Name","Product Name","Sales","Profit"]].head(10)

""" Task 5 - High Sales and High Profit

Find records where:

- Sales > 500
- Profit > 100

Both conditions must be satisfied.
"""

 result = df[
    (df("Sales") > 500) &
    (df("profit") > 500)
]

print("Number of matching records:", len(result))

display(result.head(10))

"""*italicized text*

DAY 5 LAB
"""

#superstore dataset

import kagglehub

#download latest version
path = kagglehub.dataset_download("himanshuuike/superstore-sales-dataset")

print("path the dataset files:",path)

import os

print(os.listdir(path))

import pandas as pd

df_superstore = pd.read_csv(os.path.join(path,"samplesuperstore.csv"))

print("dataset loaded successfully")

"""Task1: Single-Column Groupby Aggregation

Question: Calculate the total Sales generated by each region
"""

#Code
task1_superstore = df_superstore.groupby('Region')['Sales'].sum().reset_index()
print(task1_superstore)

"""task2:Multi Column Grupby Aggregation

Question:Calculate total Sales and Profit broken down by Category and Sub-Category
"""

#Code
task2_superstore = df_superstore.groupby(['Category','Sub-Category'])[['Sales', 'Profit']].sum().reset_index()
print(task2_superstore.head(5))

"""Task3- Multi-metric Aggregation with agg()
Question: Compute
-average Sales
-Minimum Pofit
-Maximum Profit
for each product category."""

#code
task3_superstore = df_superstore.groupby('Category').agg(
     Avg_saleas=('Sales','mean'),
     Min_Profit=('Profit','min'),
     Max_Profit=('Profit','max')
).reset_index()
print(task3_superstore)